networks:
  mynetwork:

services:

  nginx:
    container_name: nginx
    build: requirements/nginx/.
    ports:
    - "443:443"
    volumes:
    - /home/xortega/data/web:/var/www/html
    networks:
      - mynetwork
    restart: always

  wordpress:
    container_name: wordpress
    build: requirements/wordpress/.
    volumes:
    - /home/xortega/data/web:/var/www/html
    expose:
      - 9000
    networks:
      - mynetwork
    depends_on:
      - mariadb
    restart: always
  
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    volumes:
    - /home/xortega/data/database:/var/lib/mysql
    expose:
    - 3306
    networks:
      - mynetwork
    restart: always

