networks:
  mynetwork:

services:

  nginx:
    container_name: nginx
    build: requirements/nginx/.
    env_file:
      - .env
    ports:
    - "443:443"
    volumes:
    - /home/${USER}/data/web:/var/www/html
    secrets:
      - selfsigned.key
      - selfsigned.crt
    networks:
      - mynetwork
    depends_on:
      - wordpress
    restart: always

  wordpress:
    container_name: wordpress
    build: requirements/wordpress/.
    env_file:
      - .env
    volumes:
    - /home/${USER}/data/web:/var/www/html
    expose:
      - 9000
    networks:
      - mynetwork
    depends_on:
      - mariadb
    restart: always
  
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    env_file:
      - .env
    volumes:
    - /home/${USER}/data/database:/var/lib/mysql
    expose:
    - 3306
    networks:
      - mynetwork
    restart: always

secrets:
  selfsigned.key:
    file: ../secrets/selfsigned.key
  selfsigned.crt:
    file: ../secrets/selfsigned.crt