networks:
  mynetwork:

services:

  nginx:
    container_name: nginx
    build: requirements/nginx/.
    env_file:
      - .env
    ports:
    - "443:443"
    volumes:
    - /home/${USER}/data/web:/var/www/html
    secrets:
      - selfsigned.key
      - selfsigned.crt
    networks:
      - mynetwork
    depends_on:
      - wordpress
    restart: always

  wordpress:
    container_name: wordpress
    build: requirements/wordpress/.
    env_file:
      - .env
    volumes:
      - /home/${USER}/data/web:/var/www/html
    secrets:
      - wp_admin_e.txt
      - wp_admin_n.txt
      - wp_admin_p.txt
      - wp_user_p.txt
      - db_pwd.txt
    expose:
      - 9000
    networks:
      - mynetwork
    depends_on:
      - mariadb
    restart: always
  
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    env_file:
      - .env
    volumes:
      - /home/${USER}/data/database:/var/lib/mysql
    secrets:
      - db_pwd.txt    
    expose:
      - 3306
    networks:
      - mynetwork
    restart: always

secrets:
  selfsigned.key:
    file: ../secrets/selfsigned.key
  selfsigned.crt:
    file: ../secrets/selfsigned.crt
  db_pwd.txt:
    file: ../secrets/db_pwd.txt
  wp_admin_e.txt:
    file: ../secrets/wp_admin_e.txt
  wp_admin_n.txt:
    file: ../secrets/wp_admin_n.txt
  wp_admin_p.txt:
    file: ../secrets/wp_admin_p.txt
  wp_user_p.txt:
    file: ../secrets/wp_user_p.txt