networks:
  mynetwork:

services:

  nginx:
    container_name: nginx
    build: requirements/nginx/.
    ports:
    - "8080:443"
    volumes:
    - ./web:/var/www/html
    networks:
      - mynetwork
    restart: always

  wordpress:
    container_name: wordpress
    build: requirements/wordpress/.
    volumes:
    - ./web:/var/www/html
    expose:
      - 9000
    networks:
      - mynetwork
    restart: always

  
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    volumes:
    - ./database:/var/lib/mysql
    expose:
    - 3306
    networks:
      - mynetwork
    restart: always

